Repository yogeshojha/rengine, pull requests merged in 2023-12, with the labels that each got.

#1098 Fix bad nuclei config name
  README.md
  web/fixtures/default_scan_engines.yaml
  web/reNgine/definitions.py
  web/reNgine/tasks.py
  web/scanEngine/templates/scanEngine/add_engine.html
Labels: release/2.0.2

#1105 1079 disallow empty password
  web/dashboard/templates/dashboard/admin.html
  web/dashboard/views.py
Labels: release/2.0.2

#1104 fix attribute error on scan history #1103
  web/scanEngine/models.py
Labels: bug, release/2.0.2

#1106 issue-633: added already-in-org filter to target dropdown in org form
  web/targetApp/forms.py
Labels: release/2.0.2

#1107 Update Dockerfile to fix silicon incompatability
  web/Dockerfile
Labels: release/2.0.2

#1112 Spelling mistake in hackerone.html
  web/scanEngine/templates/scanEngine/settings/hackerone.html
Labels: release/2.0.2

#1111 fix(version): incorrect number in art
  web/art/reNgine.txt
Labels: release/2.0.2

#1100 Fix report generation when `Ignore Informational Vulnerabilities` checked
  web/startScan/models.py
  web/startScan/views.py
  web/templates/report/template.html
Labels: release/2.0.2

#1136 CI: update GitHub action versions
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
Labels: release/2.1.0

#514 not exposing unecessary containers publicly
  docker-compose.yml
Labels: release/2.1.0

#886 ops(migrations): add `make migrate` command
  Makefile
  install.sh
  make.bat
Labels: release/2.1.0

#994 Add stack trace into make logs if DEBUG True
  README.md
  web/celery-entrypoint.sh
  web/reNgine/settings.py
Labels: release/2.1.0

#1049 Add external IP at bottom
  web/reNgine/context_processors.py
  web/reNgine/settings.py
  web/templates/base/_items/footer.html
  web/templates/base/_items/top_nav.html
  web/templates/base/base.html
Labels: release/2.1.0

#1052 Upgrade Django to 3.2.23
  web/requirements.txt
Labels: dependencies, release/2.1.0

#1061 feat: add non-interactive installation parameter
  .env
  Makefile
  README.md
  docker-compose.yml
  install.sh
Labels: release/2.1.0

#1082 feat(admin_settings): show role description users
  web/dashboard/templates/dashboard/admin.html
Labels: enhancement, release/2.1.0

#1099 Drop infoga
  web/celery-entrypoint.sh
  web/reNgine/tasks.py
Labels: release/2.1.0

#1102 feat: Show who initiated scan
  web/api/views.py
  web/startScan/migrations/0056_auto_20231201_2354.py
  web/startScan/models.py
  web/startScan/templates/startScan/history.html
  web/startScan/views.py
Labels: release/2.1.0

#1109 Feat/multiple targets in org bulk upload via csv
  web/targetApp/templates/target/add.html
  web/targetApp/views.py
Labels: release/2.1.0

#1110 Feat/issue 492 add orgs when adding targets
  web/api/views.py
  web/static/custom/custom.js
  web/targetApp/forms.py
  web/targetApp/templates/target/add.html
  web/targetApp/views.py
Labels: release/2.1.0

#1131 Convert user input to lowercase
  update.sh
Labels: release/2.1.0

#1077 docs(readme): add ideal values for `MAX_CONCURRENCY` & `MIN_CONCURRENCY`
  README.md
Labels: release/2.1.0

#1132 fix some typos / mistakes in README
  README.md
Labels: release/2.1.0
