Repository yogeshojha/rengine, pull requests merged in 2024-08, with the labels that each got.

#1354 Implemented URL Path Exclusion Feature with Regex Support Fixes #1264
  web/reNgine/celery_custom_task.py
  web/reNgine/common_func.py
  web/reNgine/definitions.py
  web/reNgine/tasks.py
  web/startScan/templates/startScan/start_scan_ui.html
  web/startScan/views.py
  web/static/plugins/selectize/css/selectize.bootstrap3.css
  web/static/plugins/selectize/css/selectize.css
  web/static/plugins/selectize/js/standalone/selectize.min.js
Labels: release/2.2.0

#1361 feat: Consistent start scan ui across schedule scan, multiple scans. Now supports import, out of scope subdomains, starting path, excluded path for all types of scan #1357
  web/startScan/static/startScan/js/schedule-scan-wizard.js
  web/startScan/static/startScan/js/start-scan-wizard-init.js
  web/startScan/templates/organization/schedule_scan_ui.html
  web/startScan/templates/organization/start_scan.html
  web/startScan/templates/startScan/_items/scanengine_accordion.html
  web/startScan/templates/startScan/_items/schedule_scan_wizard.html
  web/startScan/templates/startScan/_items/start_scan_wizard.html
  web/startScan/templates/startScan/schedule_scan_ui.html
  web/startScan/templates/startScan/start_multiple_scan_ui.html
  web/startScan/templates/startScan/start_scan_ui.html
  web/startScan/views.py
Labels: release/2.2.0

#1363 fix: reNgine installation issue due to orjson and langchain #1362
  web/Dockerfile
Labels: release/2.1.3

#1367 chores: Add error handling for the curl command
  web/Dockerfile
Labels: release/2.1.3

#1369 Update Github Actions Workflows
  .github/workflows/auto-comment.yml
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
Labels: release/2.1.3

#1382 feat: feat ability to delete multiple scheduled scan #1360
  web/startScan/templates/startScan/history.html
  web/startScan/templates/startScan/schedule_scan_list.html
  web/startScan/urls.py
  web/startScan/views.py
Labels: release/2.2.0

#1380 feat: Enhanced Out of Scope Subdomain Checking, Support for regex in out of scope scan parameter #1358
  web/reNgine/tasks.py
  web/reNgine/utilities.py
  web/startScan/templates/startScan/_items/schedule_scan_wizard.html
  web/startScan/templates/startScan/_items/start_scan_wizard.html
Labels: release/2.2.0

#1386 feat: Prefll the scan parameters during rescan with the scan configuration values that were being used in earlier scan #1381
  web/startScan/static/startScan/js/start-scan-wizard-init.js
  web/startScan/templates/startScan/_items/scanengine_accordion.html
  web/startScan/templates/startScan/_items/start_scan_wizard.html
  web/startScan/templates/startScan/history.html
  web/startScan/views.py
Labels: release/2.2.0

#1391 Added additional templates for PDF reports #1387
  web/reNgine/charts.py
  web/reNgine/utilities.py
  web/requirements.txt
  web/startScan/templates/startScan/history.html
  web/startScan/views.py
  web/templates/report/default.html
  web/templates/report/heading.svg
  web/templates/report/modern.html
  web/templates/report/style.svg
  web/templates/report/table-content.svg
Labels: release/2.2.0

#1394 feat: Builtin notification system in reNgine #1392
  web/api/serializers.py
  web/api/urls.py
  web/api/views.py
  web/dashboard/admin.py
  web/dashboard/migrations/0002_notification.py
  web/dashboard/migrations/0003_auto_20240830_0135.py
  web/dashboard/migrations/0004_rename_notification_inappnotification.py
  web/dashboard/migrations/0005_alter_inappnotification_notification_type.py
  web/dashboard/migrations/0006_inappnotification_status.py
  web/dashboard/migrations/0007_auto_20240831_0608.py
  web/dashboard/models.py
  web/reNgine/common_func.py
  web/reNgine/definitions.py
  web/reNgine/tasks.py
  web/reNgine/utilities.py
  web/static/custom/custom.css
  web/static/custom/custom.js
  web/static/custom/notification.js
  web/static/custom/right_sidebar.js
  web/templates/base/_items/top_bar.html
  web/templates/base/base.html
Labels: release/2.2.0

#1405 Show what's new popup when update happens and new features are released #1395
  web/static/custom/update.js
  web/templates/base/base.html
Labels: release/2.2.0

#1406 feat: Add Chaos for subdomain enumeration #173
  web/Dockerfile
  web/api/views.py
  web/dashboard/admin.py
  web/dashboard/migrations/0008_chaosapikey.py
  web/dashboard/models.py
  web/dashboard/templates/dashboard/onboarding.html
  web/dashboard/views.py
  web/fixtures/default_scan_engines.yaml
  web/fixtures/external_tools.yaml
  web/reNgine/common_func.py
  web/reNgine/tasks.py
  web/scanEngine/templates/scanEngine/settings/api.html
  web/scanEngine/views.py
  web/static/custom/custom.css
Labels: release/2.2.0, release-ready
