Repository yogeshojha/rengine, pull requests merged in 2024-03, with the labels that each got.

#1198 update codeql to v3
  .github/workflows/auto-comment.yml
  .github/workflows/codeql-analysis.yml
  docker-compose.dev.yml
  docker-compose.yml
  web/dashboard/templates/dashboard/index.html
  web/reNgine/settings.py
  web/static/custom/custom.css
  web/targetApp/templates/target/list.html
  web/targetApp/templates/target/summary.html
  web/templates/base/_items/top_bar.html
  web/templates/base/login.html
Labels: Waiting for Merge, release/2.1.0

#1171 ops(make): add option to change password via `make`
  Makefile
  make.bat
Labels: enhancement, Waiting for Merge, testing, release/2.1.0

#1133 small python cleanup
  web/reNgine/context_processors.py
  web/tests/test_nmap.py
Labels: Waiting for Merge, release/2.1.0

#1119 ops(docker-compose): upgrade to 2.24.6
  install.sh
Labels: Waiting for Merge, release/2.1.0

#1161 ops(docker): use Docker Compose V2 commands
  Makefile
  install.sh
  make.bat
Labels: docker, Waiting for Merge, release/2.1.0
